version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 1
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  commit-message:
    prefix: chore
- package-ecosystem: npm
  directory: "/name-battle"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 1
  versioning-strategy: increase
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.843.0
    - 2.848.0
  commit-message:
    prefix: chore
